-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

-- admin_cobatest.cobatest definition

CREATE TABLE `cobatest` (
  `cobatest_id` bigint(11) NOT NULL AUTO_INCREMENT,
  `dtcrea` datetime DEFAULT NULL,
  `usuario_id` int(11) DEFAULT NULL,
  `anulado_sn` tinyint(4) DEFAULT NULL,
  `centro_id` bigint(11) DEFAULT NULL,
  `hivtest_namecbvct` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_citycbvct` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_testingsite` int(11) DEFAULT NULL,
  `hivtest_data1` date DEFAULT NULL,
  `hivtest_centre` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_gender` int(1) DEFAULT NULL,
  `hivtest_data2_d` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data2_m` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data2_y` int(4) DEFAULT NULL,
  `hivtest_nob` int(2) DEFAULT NULL,
  `hivtest_nos` int(2) DEFAULT NULL,
  `hivtest_initiallt` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_gender2` int(1) DEFAULT NULL,
  `hivtest_data3` date DEFAULT NULL,
  `hivtest_foreignnational` int(1) DEFAULT NULL,
  `hivtest_country` int(11) DEFAULT NULL,
  `hivtest_enter4` int(4) DEFAULT NULL,
  `hivtest_residenttourist` int(1) DEFAULT NULL,
  `hivtest_foreignStudent` int(11) DEFAULT NULL,
  `hivtest_asylumSeekingMigrant` int(11) DEFAULT NULL,
  `hivtest_undocumentedMigrant` int(11) DEFAULT NULL,
  `hivtest_foreignWorker` int(11) DEFAULT NULL,
  `hivtest_refugee` int(11) DEFAULT NULL,
  `hivtest_nationalityHolders` int(11) DEFAULT NULL,
  `hivtest_resident` int(11) DEFAULT NULL,
  `hivtest_whichOtherForeign` varchar(100) DEFAULT NULL,
  `hivtest_municipality` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_accessHealthCare` int(11) DEFAULT NULL,
  `hivtest_whichOtherHCare` varchar(100) DEFAULT NULL,
  `hivtest_reasons01` tinyint(4) DEFAULT '0',
  `hivtest_reason0101` tinyint(4) DEFAULT '0',
  `hivtest_reason0102` tinyint(4) DEFAULT '0',
  `hivtest_reason0103` tinyint(4) DEFAULT '0',
  `hivtest_reason0104` tinyint(4) DEFAULT '0',
  `hivtest_reason0105` tinyint(4) DEFAULT '0',
  `hivtest_reason0106` tinyint(4) DEFAULT '0',
  `hivtest_reason0107` tinyint(4) DEFAULT '0',
  `hivtest_reason0108` tinyint(4) DEFAULT '0',
  `hivtest_reason01text` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_reasons02` tinyint(4) DEFAULT '0',
  `hivtest_reason0201` tinyint(4) DEFAULT '0',
  `hivtest_reason0202` tinyint(4) DEFAULT '0',
  `hivtest_reason0203` tinyint(4) DEFAULT '0',
  `hivtest_reason0204` tinyint(4) DEFAULT '0',
  `hivtest_reason0205` tinyint(4) DEFAULT '0',
  `hivtest_reason0206` tinyint(4) DEFAULT '0',
  `hivtest_reason0207` tinyint(4) DEFAULT '0',
  `hivtest_reason02text` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_reasons03` tinyint(4) DEFAULT '0',
  `hivtest_reasons04` tinyint(4) DEFAULT '0',
  `hivtest_reasons05` tinyint(4) DEFAULT '0',
  `hivtest_textothers` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_reasonsb01` tinyint(4) DEFAULT '0',
  `hivtest_reasonsb02` tinyint(4) DEFAULT '0',
  `hivtest_reasonsb03` tinyint(4) DEFAULT '0',
  `hivtest_reasonsb04` tinyint(4) DEFAULT '0',
  `hivtest_reasonsb05` tinyint(4) DEFAULT '0',
  `hivtest_reasonsbtext` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_yndk01` int(1) DEFAULT NULL,
  `hivtest_hivTestP` int(11) DEFAULT NULL,
  `hivtest_data4` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data4_d` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data4_m` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data4_y` varchar(4) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_yndk03` int(1) DEFAULT NULL,
  `hivtest_yndk02` int(1) DEFAULT NULL,
  `hivtest_sxbh` int(1) DEFAULT NULL,
  `hivtest_yndk04` int(1) DEFAULT NULL,
  `hivtest_yndk05` int(1) DEFAULT NULL,
  `hivtest_yndk06` int(1) DEFAULT NULL,
  `hivtest_yndk07` int(1) DEFAULT NULL,
  `hivtest_yndk08` int(1) DEFAULT NULL,
  `hivtest_yndk09` int(1) DEFAULT NULL,
  `hivtest_yndk10` int(1) DEFAULT NULL,
  `hivtest_yndk11` int(1) DEFAULT NULL,
  `hivtest_yndk12` int(1) DEFAULT NULL,
  `hivtest_lastTime` int(11) DEFAULT NULL,
  `hivtest_data5` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data5_d` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data5_m` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data5_y` varchar(4) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_yndk13` int(1) DEFAULT NULL,
  `hivtest_yndk14` int(1) DEFAULT NULL,
  `hivtest_yndk15` int(1) DEFAULT NULL,
  `hivtest_otherAddictiveSubstances` int(11) DEFAULT NULL,
  `hivtest_whichOtherSubstances` varchar(100) DEFAULT NULL,
  `hivtest_screeningHIVTest` int(11) DEFAULT NULL,
  `hivtest_data6` date DEFAULT NULL,
  `hivtest_data6_d` varchar(2) DEFAULT NULL,
  `hivtest_data6_m` varchar(2) DEFAULT NULL,
  `hivtest_data6_y` varchar(4) DEFAULT NULL,
  `hivtest_data6_text` varchar(100) DEFAULT NULL,
  `hivtest_totu` int(1) DEFAULT NULL,
  `hivtest_yndk32` int(11) DEFAULT NULL,
  `hivtest_HIVExtraTestType` int(11) DEFAULT NULL,
  `hivtest_HIVExtraTestResult` int(11) DEFAULT NULL,
  `hivtest_str` int(1) DEFAULT NULL,
  `hivtest_yndk16` int(1) DEFAULT NULL,
  `hivtest_data7` date DEFAULT NULL,
  `hivtest_data7_d` varchar(2) DEFAULT NULL,
  `hivtest_data7_m` varchar(2) DEFAULT NULL,
  `hivtest_data7_y` varchar(4) DEFAULT NULL,
  `hivtest_data7_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk17` int(1) DEFAULT NULL,
  `hivtest_yndk18` int(1) DEFAULT NULL,
  `hivtest_data8` date DEFAULT NULL,
  `hivtest_data8_d` varchar(2) DEFAULT NULL,
  `hivtest_data8_m` varchar(2) DEFAULT NULL,
  `hivtest_data8_y` varchar(4) DEFAULT NULL,
  `hivtest_data8_text` varchar(100) DEFAULT NULL,
  `hivtest_ctr` int(1) DEFAULT NULL,
  `hivtest_yndk19` int(1) DEFAULT NULL,
  `hivtest_data9` date DEFAULT NULL,
  `hivtest_data9_d` varchar(2) DEFAULT NULL,
  `hivtest_data9_m` varchar(2) DEFAULT NULL,
  `hivtest_data9_y` varchar(4) DEFAULT NULL,
  `hivtest_data9_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk20` int(1) DEFAULT NULL,
  `hivtest_data10` date DEFAULT NULL,
  `hivtest_data10_d` varchar(2) DEFAULT NULL,
  `hivtest_data10_m` varchar(2) DEFAULT NULL,
  `hivtest_data10_y` varchar(4) DEFAULT NULL,
  `hivtest_data10_text` varchar(100) DEFAULT NULL,
  `hivtest_cd4` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_data11` date DEFAULT NULL,
  `hivtest_data11_d` varchar(2) DEFAULT NULL,
  `hivtest_data11_m` varchar(2) DEFAULT NULL,
  `hivtest_data11_y` varchar(4) DEFAULT NULL,
  `hivtest_data11_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk29` int(11) DEFAULT NULL,
  `hivtest_data18` varchar(2) DEFAULT NULL,
  `hivtest_data18_d` varchar(2) DEFAULT NULL,
  `hivtest_data18_m` varchar(2) DEFAULT NULL,
  `hivtest_data18_y` varchar(4) DEFAULT NULL,
  `hivtest_syphilisTestP` int(11) DEFAULT NULL,
  `hivtest_data18_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk21` int(1) DEFAULT NULL,
  `hivtest_data12` date DEFAULT NULL,
  `hivtest_data12_d` varchar(2) DEFAULT NULL,
  `hivtest_data12_m` varchar(2) DEFAULT NULL,
  `hivtest_data12_y` varchar(4) DEFAULT NULL,
  `hivtest_data12_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk22` int(1) DEFAULT NULL,
  `hivtest_data13` date DEFAULT NULL,
  `hivtest_data13_d` varchar(2) DEFAULT NULL,
  `hivtest_data13_m` varchar(2) DEFAULT NULL,
  `hivtest_data13_y` varchar(4) DEFAULT NULL,
  `hivtest_data13_text` varchar(100) DEFAULT NULL,
  `hivtest_totus` int(1) DEFAULT NULL,
  `hivtest_rtr` int(1) DEFAULT NULL,
  `hivtest_yndk23` int(1) DEFAULT NULL,
  `hivtest_data14` date DEFAULT NULL,
  `hivtest_data14_d` varchar(2) DEFAULT NULL,
  `hivtest_data14_m` varchar(2) DEFAULT NULL,
  `hivtest_data14_y` varchar(4) DEFAULT NULL,
  `hivtest_data14_text` varchar(100) DEFAULT NULL,
  `hivtest_sd` int(1) DEFAULT NULL,
  `hivtest_yndk24` int(1) DEFAULT NULL,
  `hivtest_data15` date DEFAULT NULL,
  `hivtest_data15_d` varchar(2) DEFAULT NULL,
  `hivtest_data15_m` varchar(2) DEFAULT NULL,
  `hivtest_data15_y` varchar(4) DEFAULT NULL,
  `hivtest_data15_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk25` int(1) DEFAULT NULL,
  `hivtest_data16` date DEFAULT NULL,
  `hivtest_data16_d` varchar(2) DEFAULT NULL,
  `hivtest_data16_m` varchar(2) DEFAULT NULL,
  `hivtest_data16_y` varchar(4) DEFAULT NULL,
  `hivtest_data16_text` varchar(100) DEFAULT NULL,
  `hivtest_tothcv` int(1) DEFAULT NULL,
  `hivtest_rtrhcv` int(1) DEFAULT NULL,
  `hivtest_yndk26` int(1) DEFAULT NULL,
  `hivtest_data17` date DEFAULT NULL,
  `hivtest_data17_d` varchar(2) DEFAULT NULL,
  `hivtest_data17_m` varchar(2) DEFAULT NULL,
  `hivtest_data17_y` varchar(4) DEFAULT NULL,
  `hivtest_data17_text` varchar(100) DEFAULT NULL,
  `hivtest_hcvd` int(1) DEFAULT NULL,
  `hivtest_yndk27` int(1) DEFAULT NULL,
  `hivtest_yndk28` int(1) DEFAULT NULL,
  `hivtest_yndk30` int(11) DEFAULT NULL,
  `hivtest_hcvTestPerformed` int(11) DEFAULT NULL,
  `hivtest_data19` date DEFAULT NULL,
  `hivtest_data19_d` varchar(2) DEFAULT NULL,
  `hivtest_data19_m` varchar(2) DEFAULT NULL,
  `hivtest_data19_y` varchar(4) DEFAULT NULL,
  `hivtest_data19_text` varchar(100) DEFAULT NULL,
  `hivtest_yndk31` int(11) DEFAULT NULL,
  `hivtest_yndk33` int(11) DEFAULT NULL,
  `hivtest_yndk34` varchar(25) DEFAULT NULL,
  `hivtest_comment` varchar(2000) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_prep` int(1) DEFAULT NULL,
  `hivtest_prep_taken` int(1) DEFAULT NULL,
  `hivtest_prep_interested` int(1) DEFAULT NULL,
  `hivtest_prep_why01` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why02` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why03` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why04` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why05` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why06` tinyint(4) DEFAULT NULL,
  `hivtest_prep_why06text` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_chemsex_drugs` int(1) DEFAULT NULL,
  `hivtest_chemsex_which_drugs01` tinyint(4) DEFAULT NULL,
  `hivtest_chemsex_which_drugs02` tinyint(4) DEFAULT NULL,
  `hivtest_chemsex_which_drugs03` tinyint(4) DEFAULT NULL,
  `hivtest_chemsex_which_drugs04` tinyint(4) DEFAULT NULL,
  `hivtest_chemsex_which_drugs05` tinyint(4) DEFAULT NULL,
  `hivtest_chemsex_inject_drug` int(1) DEFAULT NULL,
  `hivtest_belgium_type` int(1) DEFAULT NULL,
  `hivtest_belgium_status` int(1) DEFAULT NULL,
  `hivtest_belgium_status_text` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_belgium_have_residence` int(1) DEFAULT NULL,
  `hivtest_belgium_describe_ethnicity` int(1) DEFAULT NULL,
  `hivtest_belgium_describe_ethnicity_text` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_tispr_q1` int(1) DEFAULT NULL,
  `hivtest_tispr_q1_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q2` int(1) DEFAULT NULL,
  `hivtest_tispr_q2_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q3` int(1) DEFAULT NULL,
  `hivtest_tispr_q3_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q4` int(1) DEFAULT NULL,
  `hivtest_tispr_q4_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q5` int(1) DEFAULT NULL,
  `hivtest_tispr_q5_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q6` int(1) DEFAULT NULL,
  `hivtest_tispr_q6_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_total_puntuacio` float DEFAULT NULL,
  `hivtest_tispr_q7` int(1) DEFAULT NULL,
  `hivtest_tispr_q8` int(1) DEFAULT NULL,
  `hivtest_tispr_q9` int(1) DEFAULT NULL,
  `hivtest_tispr_q10` int(1) DEFAULT NULL,
  `hivtest_tispr_q10_why_text` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_tispr_q11` int(1) DEFAULT NULL,
  `hivtest_tispr_q11_why_text` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_data2` date DEFAULT NULL,
  `migra_hivtest_kp01` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_kp02` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_kp03` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_kp04` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_kp05` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_kp06` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_collector` mediumint(9) DEFAULT NULL,
  `migra_hivtest_testingsite_other` varchar(40) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_npendents` int(11) DEFAULT NULL,
  `migra_hivtest_citycbvct2` mediumint(9) DEFAULT NULL,
  `migra_hivtest_searchfield` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_report` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_ehetest` int(11) DEFAULT NULL,
  `migra_hivtest_fuptest` int(11) DEFAULT NULL,
  `migra_hivtest_wcopiat` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `migra_hivtest_wesborrat` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `hivtest_rtrhcv_backup` int(11) DEFAULT NULL,
  `hivtest_prueba_extra_vih_test` int(1) DEFAULT NULL,
  `hivtest_prueba_extra_vih_test_tipo` int(1) DEFAULT NULL,
  `hivtest_prueba_extra_vih_resultado` int(1) DEFAULT NULL,
  `previous_sti_test` int(1) DEFAULT NULL,
  `previous_sti_test_date` int(3) DEFAULT NULL,
  `previous_sti_diagnosis` int(1) DEFAULT NULL,
  `which_previous_sti_tp` tinyint(4) DEFAULT '0',
  `which_previous_sti_gono` tinyint(4) DEFAULT '0',
  `which_previous_sti_clam` tinyint(4) DEFAULT '0',
  `which_previous_sti_herp` tinyint(4) DEFAULT '0',
  `which_previous_sti_papi` tinyint(4) DEFAULT '0',
  `which_previous_sti_slg` tinyint(4) DEFAULT '0',
  `which_previous_sti_tv` tinyint(4) DEFAULT '0',
  `which_previous_sti_other` tinyint(4) DEFAULT '0',
  `which_other_previous_sti` varchar(1000) DEFAULT NULL,
  `number_sex_partners` int(3) DEFAULT NULL,
  `new_sex_partner` int(1) DEFAULT NULL,
  `sex_simultanious` int(1) DEFAULT NULL,
  `sw_typology` int(1) DEFAULT NULL,
  `sw_places` int(1) DEFAULT NULL,
  `sw_years` int(2) DEFAULT NULL,
  `sample_collected` int(1) DEFAULT NULL,
  `vaginal_self_sample` int(1) DEFAULT NULL,
  `rectal_self_sample` int(1) DEFAULT NULL,
  `pharyngeal_self_sample` int(1) DEFAULT NULL,
  `result_vaginal_self_sample` int(1) DEFAULT NULL,
  `positive_clam_vaginal` tinyint(4) DEFAULT '0',
  `positive_gono_vaginal` tinyint(4) DEFAULT '0',
  `positive_myco_vaginal` tinyint(4) DEFAULT '0',
  `positive_urea_vaginal` tinyint(4) DEFAULT '0',
  `positive_trico_vaginal` tinyint(4) DEFAULT '0',
  `positive_herp_vaginal` tinyint(4) DEFAULT '0',
  `result_rectal_self_sample` int(1) DEFAULT NULL,
  `positive_clam_rectal` tinyint(4) DEFAULT '0',
  `positive_gono_rectal` tinyint(4) DEFAULT '0',
  `positive_myco_rectal` tinyint(4) DEFAULT '0',
  `positive_ureal_rectal` tinyint(4) DEFAULT '0',
  `positive_urea_rectal` tinyint(4) DEFAULT '0',
  `positive_trico_rectal` tinyint(4) DEFAULT '0',
  `positive_herp_rectal` tinyint(4) DEFAULT '0',
  `result_pharyngeal_self_sample` int(1) DEFAULT NULL,
  `positive_clam_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_gono_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_myco_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_ureal_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_urea_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_trico_pharyngeal` tinyint(4) DEFAULT '0',
  `positive_herp_pharyngeal` tinyint(4) DEFAULT '0',
  `treatment` int(1) DEFAULT NULL,
  `treatment_date` datetime DEFAULT NULL,
  `sti_comments` varchar(1000) DEFAULT NULL,
  `sample_collected_date` datetime DEFAULT NULL,
  `deriv_esp` int(1) DEFAULT NULL,
  `its_previous_sti_test` int(1) DEFAULT NULL,
  `its_previous_sti_test_date` int(3) DEFAULT NULL,
  `its_previous_sti_diagnosis` int(1) DEFAULT NULL,
  `its_which_previous_sti_tp` int(1) DEFAULT NULL,
  `its_which_previous_sti_gono` int(1) DEFAULT NULL,
  `its_which_previous_sti_clam` int(1) DEFAULT NULL,
  `its_which_previous_sti_herp` int(1) DEFAULT NULL,
  `its_which_previous_sti_papi` int(1) DEFAULT NULL,
  `its_which_previous_sti_slg` int(1) DEFAULT NULL,
  `its_which_previous_sti_tv` int(1) DEFAULT NULL,
  `its_which_previous_sti_other` int(1) DEFAULT NULL,
  `its_which_other_previous_sti` varchar(1000) DEFAULT NULL,
  `its_number_sex_partners` int(3) DEFAULT NULL,
  `its_new_sex_partner` int(1) DEFAULT NULL,
  `its_sex_simultanious` int(1) DEFAULT NULL,
  `its_ct_test` int(1) DEFAULT NULL,
  `its_ct_sample_date` datetime DEFAULT NULL,
  `its_ct_orina_sample` int(1) DEFAULT NULL,
  `its_ct_genital_sample` int(1) DEFAULT NULL,
  `its_ct_rectal_sample` int(1) DEFAULT NULL,
  `its_ct_pharyngeal_sample` int(1) DEFAULT NULL,
  `its_ct_test_type` int(1) DEFAULT NULL,
  `its_ct_test_result` int(1) DEFAULT NULL,
  `its_ct_treatment` int(1) DEFAULT NULL,
  `its_ct_treatment_date` datetime DEFAULT NULL,
  `its_gono_test` int(1) DEFAULT NULL,
  `its_gono_sample_date` datetime DEFAULT NULL,
  `its_gono_orina_sample` int(1) DEFAULT NULL,
  `its_gono_genital_sample` int(1) DEFAULT NULL,
  `its_gono_rectal_sample` int(1) DEFAULT NULL,
  `its_gono_pharyngeal_sample` int(1) DEFAULT NULL,
  `its_gono_test_type` int(1) DEFAULT NULL,
  `its_gono_test_result` int(1) DEFAULT NULL,
  `its_gono_treatment` int(1) DEFAULT NULL,
  `its_gono_treatment_date` datetime DEFAULT NULL,
  `its_sti_comments` varchar(1000) DEFAULT NULL,
  `mon_relazione` int(1) DEFAULT NULL,
  `num_de_partner12mes` int(1) DEFAULT NULL,
  `liv_istruzione` int(1) DEFAULT NULL,
  `sesso_gruppo` int(1) DEFAULT NULL,
  `cond_sex_toys` int(1) DEFAULT NULL,
  `fisting` int(1) DEFAULT NULL,
  `ingoiare_sperma` int(1) DEFAULT NULL,
  `sesso_penetrativo_con_hivpos` int(1) DEFAULT NULL,
  `sesso_penetrativo_con_hivpos_si` int(1) DEFAULT NULL,
  `altro_txt` varchar(255) DEFAULT NULL,
  `evitsesso` int(1) DEFAULT NULL,
  PRIMARY KEY (`cobatest_id`),
  KEY `fk_usuario_form_idx` (`usuario_id`),
  KEY `fk_centro_form_idx` (`centro_id`),
  KEY `cobatest_lugar_realizacion_prueba_fk` (`hivtest_testingsite`),
  CONSTRAINT `cobatest_lugar_realizacion_prueba_FK` FOREIGN KEY (`hivtest_testingsite`) REFERENCES `lugar_realizacion_prueba` (`codigo`),
  CONSTRAINT `fk_centro_form` FOREIGN KEY (`centro_id`) REFERENCES `hg_centro` (`centro_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_form` FOREIGN KEY (`usuario_id`) REFERENCES `fos_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=126562 DEFAULT CHARSET=utf8;
